



options("scipen"=6, "digits"=6)
##' Extract hazard ratio and confidence intervals from a coxph object
##'
##' Convenience function to extract hazard ratio and confidence intervals from a coxph object,
##' as generated by a call to coxph(), comparing survival times between two groups
##' @param coxphData coxph object; coxphData <- coxph(Surv(TTE, Cens) ~ group, data=df)
##' @author Dorothee Nickles
##' @export
##' @import survival
getHRandCIfromCoxph <- function(coxphData) {
  
  stopifnot(is(coxphData, "coxph"))
  
  tmp <- cbind(
    summary(coxphData)$coef[,
                            c("Pr(>|z|)", "exp(coef)"), 
                            drop=FALSE],
    summary(coxphData)$conf[,
                            c("lower .95", "upper .95"), 
                            drop=FALSE]
  )
  colnames(tmp) <- c("P","HR","CI_low_0.95","CI_up_0.95")
  return(round(tmp,digits=4))
}
##########################################################


##' Extract hazard ratio and confidence intervals from a coxph object of subgroup analysis
##'
##' @param pdata     data combine variables, time, and status;
##' @param variable  object that have several levles;
##' @param time      follow up 
##' @param status    outcome event
##' @param object    that use to calculate coxph fit 
##' @author Dongqiang Zeng 
##' @export 
##' @import survival
###########################################################
###########################################################
Subgroup_survival_analysis<-function(pdata,time="time",status= "status",variable,object){
  P<-1;HR<-1;CI_low_0.95<-1;CI_up_0.95<-1;Cindex<-1;Auc<-1;
  result<-data.frame(P,HR,CI_low_0.95,CI_up_0.95,Cindex,Auc,row.names = "defult");
  pdata<-as.data.frame(pdata);
  for (sig in variable) {
    ind<-which(colnames(pdata)==sig);
    tmp<-pdata[!is.na(pdata[,ind]),];
    if(dim(tmp)[1]==0) 
      next;
    tmp[,ind]<-as.factor(as.character(tmp[,ind]));
    result2<-data.frame(P,HR,CI_low_0.95,CI_up_0.95,Cindex,Auc,row.names = "defult");
    nl<-nlevels(tmp[,ind]);
    for (i in 1:nl) {
      tmp1<-tmp[as.character(tmp[,ind])==names(summary(tmp[,ind]))[i],];
      if(dim(tmp1)[1]==0) 
        next;
      fit<-coxph(Surv(tmp1[,time],tmp1[,status])~tmp1[,object],data = tmp1);
      result1<-getHRandCIfromCoxph(fit);
      result1<-as.data.frame( result1);
      cindex1<-concordance.index(tmp1[,object],
                                 surv.time = tmp1[,time],
                                 surv.event = tmp1[,status],
                                 method = "noether");
      result1$Cindex<-paste0(round(cindex1$c.index,3),"(",round(cindex1$lower,3),"-",round(cindex1$upper,3),")");
      ROC1<-roc(tmp1[,status],tmp1[,object],ci=T);
      result1$Auc<-paste0(round(ROC1$ci[2],3),"(",round(ROC1$ci[1],3),"-",round(ROC1$ci[3],3),")");
      rownames(result1)<-paste(sig,levels(tmp[,ind])[i],sep = "_");
      result2<-rbind(result2,result1);
    }
    result<-rbind(result,result2);
  }
  result[result>100]<-Inf
  return(result[-c(grep(rownames(result),pattern ="defult")),])
}
##############################################################
